### ISSUE TITLE
Fails to install on bionic machines

### ISSUE THREAD

**Issue by canonikamal** [canonical/charm-sysconfig#79]
Hello

The sysconfig charm installation or refresh to latest/stable rev 36 fails on bionic machines with below error:

```
2024-11-29 06:34:43 DEBUG unit.sysconfig/10.install logger.go:60   Complete output from command /var/lib/juju/agents/unit-sysconfig-10/.venv/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-lpjps0xm --no-warn-script-location --no-binary :none: --only-binary :none: --no-index --find-links wheelhouse --:
2024-11-29 06:34:43 DEBUG unit.sysconfig/10.install logger.go:60   ERROR: You must give at least one requirement to install (maybe you meant "pip install wheelhouse"?)
2024-11-29 06:34:43 DEBUG unit.sysconfig/10.install logger.go:60   
2024-11-29 06:34:43 DEBUG unit.sysconfig/10.install logger.go:60   ----------------------------------------
2024-11-29 06:34:43 WARNING unit.sysconfig/10.install logger.go:60 Command "/var/lib/juju/agents/unit-sysconfig-10/.venv/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-lpjps0xm --no-warn-script-location --no-binary :none: --only-binary :none: --no-index --find-links wheelhouse --" failed with error code 1 in None
2024-11-29 06:34:43 WARNING unit.sysconfig/10.install logger.go:60 Traceback (most recent call last):
2024-11-29 06:34:43 WARNING unit.sysconfig/10.install logger.go:60   File "/var/lib/juju/agents/unit-sysconfig-10/charm/hooks/install", line 8, in <module>
2024-11-29 06:34:43 WARNING unit.sysconfig/10.install logger.go:60     basic.bootstrap_charm_deps()
2024-11-29 06:34:43 WARNING unit.sysconfig/10.install logger.go:60   File "lib/charms/layer/basic.py", line 200, in bootstrap_charm_deps
2024-11-29 06:34:43 WARNING unit.sysconfig/10.install logger.go:60     _update_if_newer(pip, pre_install_pkgs)
2024-11-29 06:34:43 WARNING unit.sysconfig/10.install logger.go:60   File "lib/charms/layer/basic.py", line 365, in _update_if_newer
2024-11-29 06:34:43 WARNING unit.sysconfig/10.install logger.go:60     pkg], env=_get_subprocess_env())
2024-11-29 06:34:43 WARNING unit.sysconfig/10.install logger.go:60   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
2024-11-29 06:34:43 WARNING unit.sysconfig/10.install logger.go:60     raise CalledProcessError(retcode, cmd)
2024-11-29 06:34:43 WARNING unit.sysconfig/10.install logger.go:60 subprocess.CalledProcessError: Command '['/var/lib/juju/agents/unit-sysconfig-10/.venv/bin/pip', 'install', '-U', '--no-index', '-f', 'wheelhouse', 'setuptools']' returned non-zero exit status 1.
2024-11-29 06:34:43 ERROR juju.worker.uniter.operation runhook.go:153 hook "install" (via explicit, bespoke hook script) failed: exit status 1
```

Charm was deployed on cloud maas.
Used ubuntu charm as well with series bionic to attach its units to sysconfig latest/stable(rev 36) [current rev at the moment] and the result is the same as show above.
Also, tried the channel latest/edge (rev 68), still the same issue.

Thanks & regards
Kamal Bhaskar

**Comment by jneo8** [comment]
The pip version for bionic is `18.1`, I manual upgrade it to 20.0.2 fix the issue will fix the issue.

**Comment by jneo8** [comment]
Reproduce on bionic, revision 57:

```
root@juju-e6ddee-0:/var/lib/juju/agents/unit-sysconfig-2/charm# /var/lib/juju/agents/unit-sysconfig-2/.venv/bin/pip install -U --no-index -f wheelhouse setuptools -v --no-clean
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/pip-ephem-wheel-cache-rkvnmpn_
Created temporary directory: /tmp/pip-req-tracker-u1off8me
Created requirements tracker '/tmp/pip-req-tracker-u1off8me'
Created temporary directory: /tmp/pip-install-88zea12f
Looking in links: wheelhouse
0 location(s) to search for versions of setuptools:
Skipping link wheelhouse (from -f); not a file
Skipping link file:///var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/pbr-6.1.0.tar.gz; Missing project version for setuptools
Skipping link file:///var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/Cython-0.29.37.tar.gz; Missing project version for setuptools
Skipping link file:///var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/MarkupSafe-2.0.1.tar.gz; Missing project version for setuptools
Found link file:///var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/setuptools_scm-1.17.0.tar.gz, version: scm-1.17.0
Skipping link file:///var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/wheel-0.33.6.tar.gz; Missing project version for setuptools
Skipping link file:///var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/pip-18.1.tar.gz; Missing project version for setuptools
Skipping link file:///var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/charms_reactive-1.5.3.tar.gz; Missing project version for setuptools
Skipping link file:///var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/pyaml-21.10.1.tar.gz; Missing project version for setuptools
Skipping link file:///var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/PyYAML-5.3.1.tar.gz; Missing project version for setuptools
Skipping link file:///var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/netaddr-0.7.19.tar.gz; Missing project version for setuptools
Skipping link file:///var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/charmhelpers-1.2.1.tar.gz; Missing project version for setuptools
Skipping link file:///var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/flit_core-3.10.1.tar.gz; Missing project version for setuptools
Skipping link file:///var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/Jinja2-3.0.3.tar.gz; Missing project version for setuptools
Skipping link file:///var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/immutables-0.15.tar.gz; Missing project version for setuptools
Found link file:///var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/setuptools-59.6.0.tar.gz, version: 59.6.0
Local files found: /var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/setuptools-59.6.0.tar.gz, /var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/setuptools_scm-1.17.0.tar.gz
Using version 59.6.0 (newest of versions: 59.6.0)
Collecting setuptools
  0 location(s) to search for versions of setuptools:
  Found link file:///var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/setuptools_scm-1.17.0.tar.gz, version: scm-1.17.0
  Found link file:///var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/setuptools-59.6.0.tar.gz, version: 59.6.0
  Local files found: /var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/setuptools-59.6.0.tar.gz, /var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/setuptools_scm-1.17.0.tar.gz
  Using version 59.6.0 (newest of versions: 59.6.0)
  Added setuptools from file:///var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/setuptools-59.6.0.tar.gz to build tracker '/tmp/pip-req-tracker-u1off8me'
  Created temporary directory: /tmp/pip-build-env-0a5hmkva
  Installing build dependencies ...   Running command /var/lib/juju/agents/unit-sysconfig-2/.venv/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-0a5hmkva --no-warn-script-location -v --no-binary :none: --only-binary :none: --no-index --find-links wheelhouse --
  Ignoring indexes: https://pypi.org/simple
  Created temporary directory: /tmp/pip-ephem-wheel-cache-ocerk9yx
  Re-using requirements tracker '/tmp/pip-req-tracker-u1off8me'
  Created temporary directory: /tmp/pip-install-3ee873kc
  Cleaning up...
  Cleaned build tracker '/tmp/pip-req-tracker-u1off8me'
  ERROR: You must give at least one requirement to install (maybe you meant "pip install wheelhouse"?)
  Exception information:
  Traceback (most recent call last):
    File "/var/lib/juju/agents/unit-sysconfig-2/.venv/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 143, in main
      status = self.run(options, args)
    File "/var/lib/juju/agents/unit-sysconfig-2/.venv/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 293, in run
      self.name, wheel_cache
    File "/var/lib/juju/agents/unit-sysconfig-2/.venv/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 248, in populate_requirement_set
      dict(opts, links=' '.join(options.find_links)))
  pip._internal.exceptions.CommandError: You must give at least one requirement to install (maybe you meant "pip install wheelhouse"?)
error
Removed setuptools from file:///var/lib/juju/agents/unit-sysconfig-2/charm/wheelhouse/setuptools-59.6.0.tar.gz from build tracker '/tmp/pip-req-tracker-u1off8me'
Removed build tracker '/tmp/pip-req-tracker-u1off8me'
Command "/var/lib/juju/agents/unit-sysconfig-2/.venv/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-0a5hmkva --no-warn-script-location -v --no-binary :none: --only-binary :none: --no-index --find-links wheelhouse --" failed with error code 1 in None
Exception information:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-sysconfig-2/.venv/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/var/lib/juju/agents/unit-sysconfig-2/.venv/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 318, in run
    resolver.resolve(requirement_set)
  File "/var/lib/juju/agents/unit-sysconfig-2/.venv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/var/lib/juju/agents/unit-sysconfig-2/.venv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/var/lib/juju/agents/unit-sysconfig-2/.venv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/var/lib/juju/agents/unit-sysconfig-2/.venv/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 298, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/var/lib/juju/agents/unit-sysconfig-2/.venv/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 109, in prep_for_dist
    "Installing build dependencies"
  File "/var/lib/juju/agents/unit-sysconfig-2/.venv/lib/python3.6/site-packages/pip/_internal/build_env.py", line 122, in install_requirements
    call_subprocess(args, show_stdout=False, spinner=spinner)
  File "/var/lib/juju/agents/unit-sysconfig-2/.venv/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/var/lib/juju/agents/unit-sysconfig-2/.venv/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-0a5hmkva --no-warn-script-location -v --no-binary :none: --only-binary :none: --no-index --find-links wheelhouse --" failed with error code 1 in None

```

**Comment by jneo8** [comment]
This issue is relate to  dependency version, https://github.com/canonical/layer-basic/blob/24324f8dab91bb304f7400dadc263ac6106268cb/wheelhouse.txt

Now we pin `setuptool>42` and `flit-core>=3` cause this issue. It work for focal and jammy but not for bionic.

And there seems no way for us to choose different package version for different series if we use the same wheelhouse.txt file.

cc @Pjack , do you think we should create another branch here for bionic?

**Comment by jneo8** [comment]
The change in on https://github.com/canonical/charm-sysconfig/commit/08acb8805990e1eaccdd077c8aea2cc1452c1b0c

The charm revision < `34`, release before 2024/04/26 should works.
